"""backend scenario actions; expectations are supplied by JSON."""
import json,os,re,time,socket,http.client,shutil,subprocess,sys,tempfile,threading
from pathlib import Path
from urllib.parse import urlparse
from dsh_test_harness.desktop import Desktop
from dsh_test_harness.wait import until
from ui import *
PACK=Path(__file__).resolve().parents[2];ROOT=PACK.parent

def state_wait(self,step):
    op=step["op"];p=self.page;b=self.backend
    latest=None
    def observed():
        nonlocal latest
        latest=b.core.store.get('task',step['task_id'])
        return latest if latest and latest['status']==step['status'] else None
    try:return until(observed,step.get('timeout',30))
    except TimeoutError as error:
        facts={key:(latest or {}).get(key) for key in ('id','status','standby','no_input_reports','start_at','end_at')}
        raise TimeoutError('Expected task status '+step['status']+'; last observed '+json.dumps(facts)) from error

def shell_run(self,step):
    op=step["op"];p=self.page;b=self.backend
    argv = step.get('argv')
    if argv is None:
        if step.get('shell') == 'powershell' or (step.get('shell') is None and sys.platform == 'win32'):
            argv = ['powershell', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', '[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new(); ' + step['command']]
        else:
            argv = ['bash', '-lc', step['command']] if step.get('sudo') is None else ['sudo', 'bash', '-lc', step['command']] if step.get('sudo') else ['bash', '-lc', step['command']]
    result = subprocess.run(argv, capture_output=True, cwd=str(ROOT), timeout=step.get('timeout', 120), creationflags=getattr(subprocess, 'CREATE_NO_WINDOW', 0))
    output = (result.stdout + result.stderr).decode('utf-8', 'replace')
    if result.returncode and (not step.get('allow_failure')):
        raise RuntimeError('shell 失败(' + str(result.returncode) + ')：' + output[-500:])
    return {'code': result.returncode, 'output': output}

def state_read(self,step):
    op=step["op"];p=self.page;b=self.backend
    state=b.core.state()
    if step.get('task_id'):
        task_id=step['task_id']
        state={**state,**{key:[row for row in state.get(key,[]) if row.get('id' if key in ('tasks','live') else 'task_id')==task_id] for key in ('tasks','live','reports','alerts')}}
    return state

def state_fields(self,step):
    op=step["op"];p=self.page;b=self.backend
    return until(lambda: task if (task := b.core.store.get('task', step['task_id'])) and all((task.get(k) == v for k, v in step['expected'].items())) else None, step.get('timeout', 30))

def backend_restart(self,step):
    op=step["op"];p=self.page;b=self.backend
    b.restart()
    return b.core.state()

def report_drain(self,step):
    # Establish an observation boundary after a fixture/UI change. Product
    # delivery continues normally; do not release or rewrite report state.
    reports=self.backend.core.store.all('report')
    self.observed_reports.update(r['id'] for r in reports)
    return {'observed_before_next_phase':[r['id'] for r in reports]}

def report_preview(self,step):
    # Legacy spelling: observe the next report generated by the real service.
    seen=getattr(self,'observed_reports',set())
    def observed():
        return next((r for r in self.backend.core.store.all('report') if r['id'] not in seen),None)
    report=until(observed,step.get('timeout',60))
    seen.add(report['id']);self.observed_reports=seen
    return report

def report_release(self,step):
    # No release endpoint: the real DSH heartbeat owns delivery and review.
    return until(lambda:r if (r:=self.backend.core.store.get('report',step['report_id'])) and r['status']=='reviewed' else None,step.get('timeout',60))

def evidence_inspect(self,step):
    op=step["op"];p=self.page;b=self.backend
    r = b.core.store.get('report', step['report_id'])
    export = b.core.store.get('export', r['id'])
    if not export:
        raise AssertionError('Formal service did not export evidence for '+str(r['id']))
    folder = Path(export['folder'])
    try:
        effective = json.loads((folder / 'timeline.json').read_text(encoding='utf-8'))
    except OSError as error:
        diagnostic={'error':str(error),'path':str(folder/'timeline.json'),'pid':os.getpid()}
        if os.name=='nt':
            import ctypes
            diagnostic['elevated']=bool(ctypes.windll.shell32.IsUserAnAdmin())
            diagnostic['acl']=[{'path':str(path),'result':subprocess.run(['icacls',str(path)],capture_output=True,text=True,encoding='utf-8',errors='replace',creationflags=subprocess.CREATE_NO_WINDOW).stdout}
                               for path in (folder.parent.parent,folder.parent,folder,folder/'timeline.json')]
            from dsh_test_harness.vm.input import request
            diagnostic['observer_acl']=request('file_acl',paths=[str(p) for p in (folder.parent.parent.parent,folder.parent.parent,folder.parent,folder,folder/'timeline.json')])['acl']
            diagnostic['identity']=subprocess.run(['whoami','/user'],capture_output=True,text=True,encoding='utf-8',errors='replace',creationflags=subprocess.CREATE_NO_WINDOW).stdout
        (self.out/'evidence-read-failure.json').write_text(json.dumps(diagnostic,ensure_ascii=False,indent=2),encoding='utf-8')
        raise
    objects = [o for s in effective['segments'] for o in s['objects']]
    target = next(((ref, e) for ref, e in reversed(list(effective['evidence'].items())) if e.get('title') == step.get('target_title') and e.get('visible') and (e.get('ui_text') or e.get('screenshot'))), None)
    if step.get('target_entity'):
        identity=self.entities.items[step['target_entity']]
        target=next(((ref,e) for ref,e in reversed(list(effective['evidence'].items())) if e.get('id')==identity['window_id'] and e.get('pid')==identity['pid']),None)
        if target is None:raise AssertionError('Formal report lacks window target for '+step['target_entity'])
    fixture_program_files = {name: file for name, file in export['program_files'].items() if any((e.get('title') == step.get('target_title') for e in json.loads((folder / file).read_text(encoding='utf-8')).get('evidence', {}).values()))}
    heartbeats = [m for request in self.model.requests for m in request['messages'] if m['role'] == 'user' and r['id'] in str(m)]
    images = [part for m in heartbeats if isinstance(m['content'], list) for part in m['content'] if part.get('type') in ('file', 'image_url')]
    image_valid = bool(images) and all((i.get('type') == 'image_url' or i.get('file_id') in self.model.files for i in images))
    result = {'folder': str(folder), 'task_folder': str(folder.parent), 'overview_file': str(folder / 'overview.json'), 'timeline_file': str(folder / 'timeline.json'), 'raw_seconds_unrounded': sum(s['real_duration_seconds'] for s in r['raw']['segments']), 'raw_seconds': round(sum(s['real_duration_seconds'] for s in r['raw']['segments']),3), 'effective_seconds': effective['effective_observed_seconds'], 'image_count': len(list((folder / 'screenshots').glob('*.png'))), 'program_files': export['program_files'], 'fixture_program_files': fixture_program_files, 'objects': objects, 'evidence': effective['evidence'], 'full_desktop_image': (effective.get('desktop_screenshot') or {}).get('scope') == 'full_desktop' and (folder / effective['desktop_screenshot']['path']).is_file(), 'fixture_window_ids': sorted({e['id'] for e in effective['evidence'].values() if e.get('kind') == 'window' and e.get('title') == step.get('target_title') and e.get('screenshot') and (folder / e['screenshot']['path']).is_file()}), 'has_focus': any((o.get('focused') and o.get('visible') for o in objects)), 'model_image_valid': image_valid, 'heartbeat_text': '\n'.join((str(m['content']) if isinstance(m['content'], str) else '\n'.join((v.get('text', '') for v in m['content'])) for m in heartbeats)), 'system_text': '\n'.join((str(m['content']) for req in self.model.requests for m in req['messages'] if m['role'] == 'system')), 'model': self.model.requests[0]['model'], 'reasoning_effort': self.model.requests[0].get('reasoning_effort'), 'target_ref': target[0] if target else None, 'target_id': target[1]['id'] if target else None}
    result['browser_snapshots'] = effective.get('browser_snapshots', [])
    result['browser_semantic_status'] = effective.get('browser_semantic_status', [])
    result['browser_semantic_text'] = '\n'.join(r.get('snapshot', {}).get('text', '') for r in result['browser_snapshots'])
    (self.out / 'evidence-observation.json').write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
    return result

def report_wait(self,step):
    latest=[]
    def observed():
        nonlocal latest
        reports=self.backend.core.store.all('report')
        latest=[r for r in reports if r['task_id']==step['task_id']][-5:]
        return next((r for r in reversed(reports) if r['task_id']==step['task_id']
                     and r.get('status')==step.get('status','reviewed')
                     and r['id'] not in step.get('exclude',[])
                     and r.get('created_at',0)>step.get('created_after',0)
                     and (not step.get('phase') or r.get('phase')==step['phase'])
                     and (not step.get('sampled_after') or (r.get('raw',{}).get('real_end') or 0)>step['sampled_after'])
                     and (not step.get('sampled_from_after') or (r.get('raw',{}).get('real_start') or 0)>step['sampled_from_after'])
                     and len(r.get('raw',{}).get('source_sample_ids',[]))>=step.get('minimum_samples',0)
                     and r.get('raw',{}).get('unobserved_gap_seconds',0)>=step.get('minimum_gap_seconds',0)
                     and (not step.get('metadata_after') or any(e.get('id')==step['window_id'] and (e.get('metadata_captured_at') or 0)>step['metadata_after'] for e in r.get('raw',{}).get('evidence',{}).values()))
                     and (not step.get('text_contains') or any(e.get('id')==step['window_id'] and step['text_contains'] in (e.get('ui_text') or '') for e in r.get('raw',{}).get('evidence',{}).values()))
                     and (not step.get('screenshot_scope') or any(e.get('id')==step['window_id'] and (e.get('screenshot') or {}).get('scope')==step['screenshot_scope'] for e in r.get('raw',{}).get('evidence',{}).values()))
                     and (not step.get('detail_after') or any(e.get('id')==step['window_id'] and (e.get('details_captured_at') or 0)>step['detail_after'] for e in r.get('raw',{}).get('evidence',{}).values()))),None)
    try:return until(observed,step.get('timeout',60),wait=lambda seconds:self.page.wait_for_timeout(seconds*1000))
    except TimeoutError:
        evidence=[]
        for r in latest:
            raw=r.get('raw',{})
            evidence.append({'id':r['id'],'status':r.get('status'),'phase':r.get('phase'),
                'created_at':r.get('created_at'),'real_end':raw.get('real_end'),
                'samples':len(raw.get('source_sample_ids',[])),
                'windows':[{**{k:e.get(k) for k in ('id','title','visible','focused','metadata_captured_at','details_captured_at','ui_text_error','screenshot_error')},'screenshot_scope':(e.get('screenshot') or {}).get('scope')}
                           for e in raw.get('evidence',{}).values() if not step.get('window_id') or e.get('id')==step['window_id']]})
        diagnostic={'expected':step,'reports':evidence,'state':self.backend.state()}
        diagnostic['state_observation']=getattr(self.backend,'state_observation',None)
        if os.name=='nt':
            import psutil
            processes=[]
            for process in psutil.process_iter(['pid','ppid','cmdline','create_time','status']):
                if any('windows_service.py' in arg for arg in process.info.get('cmdline') or []):
                    processes.append({k:v for k,v in process.info.items() if k!='cmdline'})
            diagnostic['service_processes']=processes
        (self.out/(step.get('id','report-wait')+'-timeout.json')).write_text(json.dumps(diagnostic,ensure_ascii=False,indent=2),encoding='utf-8')
        raise

def report_target(self,step):
    report=self.backend.core.store.get('report',step['report_id'])
    entity=self.entities.items[step['entity']]
    candidates=report['effective']['evidence']
    # Stable native ID/PID from the fixture, never a title guess.
    kind=step.get('kind','window')
    matches=[{'ref':ref,'evidence':e} for ref,e in candidates.items()
             if e.get('kind')==kind and e.get('pid')==entity['pid']
             and ((kind=='browser_tab' and ((e.get('tab_id') is not None and str(e['tab_id'])==str(entity.get('tab_id')))
                                           or (e.get('tab_id') is None and entity.get('tab_id') is None and e.get('native_window_id')==entity['window_id'])))
                  or (kind=='window' and (e.get('id')==entity['window_id'] or str(e.get('native_id'))==entity['window_id'].split(':')[-1])))]
    if not matches:raise AssertionError('Formal report lacks '+kind+' target for '+step['entity'])
    # Evidence keys may be sorted during serialization; their order is not time.
    return max(matches,key=lambda row:row['evidence'].get('source_sample_id',0))

def connection_probe(self,step):
    # Explicit failure injection: an unused endpoint, never a replacement service.
    import urllib.request
    with urllib.request.urlopen(step['url'],timeout=step.get('timeout',3)) as response:
        return {'status':response.status}

def session_save(self,step):
    directory=Path(os.environ['DSH_TEST_SESSION_DIRECTORY'])
    saved={key:self.values[key] for key in step['keys']}
    (directory/'checkpoint.json').write_text(json.dumps(saved,ensure_ascii=False),encoding='utf-8')
    # The next phase owns cleanup of this exact task; no pre-existing task is touched.
    self.backend.original_tasks.add(saved['task']['value']['id'])
    self.backend.defer_settings_restore=True
    return saved

def session_load(self,step):
    saved=json.loads((Path(os.environ['DSH_TEST_SESSION_DIRECTORY'])/'checkpoint.json').read_text(encoding='utf-8'))
    self.values.update(saved)
    return saved

def service_observe(self,step):
    """Read service reachability and processes without waking or keeping it alive."""
    import psutil
    started=time.monotonic();samples=[]
    while True:
        row={'elapsed':round(time.monotonic()-started,3),'at':time.time()}
        try:
            state=self.backend.request('/state',{})
            row.update(reachable=True,live_tasks=[t['id'] for t in state.get('live',[])],capture_state=state.get('capture_state'),capture_error=state.get('capture_error'),last_sample_at=state.get('last_sample_at'))
        except (OSError,RuntimeError,http.client.HTTPException) as error:
            row.update(reachable=False,error=f'{type(error).__name__}: {error}')
        row['status_files']={}
        for name in ('status.json','settings.json'):
            try:
                stat=(self.backend.directory/name).stat()
                row['status_files'][name]=[stat.st_mtime_ns,stat.st_ctime_ns,stat.st_size]
            except FileNotFoundError:row['status_files'][name]=None
        processes=[]
        for process in psutil.process_iter(['pid','create_time','cmdline']):
            command=process.info['cmdline'] or []
            if any(Path(arg).name in ('chat_service.py','windows_service.py','chat_sensor.py') for arg in command):
                processes.append({'pid':process.pid,'created_at':process.info['create_time']})
        row['processes']=processes
        if sys.platform!='win32':
            from focus_demo.desktop_bridge import call
            try:row['bridge']=call('status')
            except Exception as error:row['bridge']={'error':str(error)}
        samples.append(row)
        remaining=step.get('seconds',0)-(time.monotonic()-started)
        if remaining<=0:break
        time.sleep(min(step.get('interval',.25),remaining))
    captures=[r.get('last_sample_at') for r in samples if r.get('reachable')]
    bridge_delta=({key:samples[-1]['bridge'][key]-samples[0]['bridge'][key] for key in ('snapshots','screenshots')} if all(key in row.get('bridge',{}) for row in (samples[0],samples[-1]) for key in ('snapshots','screenshots')) else None) if sys.platform!='win32' else {}
    return {'samples':samples,'last':samples[-1],'status_file_changes':sum(a['status_files']!=b['status_files'] for a,b in zip(samples,samples[1:])),'sample_changes':sum(a!=b for a,b in zip(captures,captures[1:])),'bridge_delta':bridge_delta,'capture_changes':max([sum(a!=b for a,b in zip(captures,captures[1:])),*(bridge_delta or {}).values()])}

def sample_inspect(self,step):
    samples=self.backend.core.store.read('samples',step['task_id'])
    samples=[r for r in samples if r['ts']>step.get('after',0)]
    intervals=[b['mono']-a['mono'] for a,b in zip(samples,samples[1:])]
    identity=self.entities.items.get(step.get('entity'),{})
    windows=[w for r in samples for w in r['desktop'].get('windows',[]) if w['id']==identity.get('window_id')]
    shots=[w['screenshot'] for w in windows if w.get('screenshot')]
    texts=[w.get('ui_text','') for w in windows if w.get('ui_text')]
    logs=[log for w in windows for log in w.get('logs',[]) if log.get('source')=='open_regular_log_file']
    semantics=[r.get('browser',{}).get('semantic',{}) for r in samples]
    metrics={'image_count':len(shots),'max_width':max((p['width'] for p in shots),default=0),'max_height':max((p['height'] for p in shots),default=0),
             'text_count':len(texts),'max_text_chars':max(map(len,texts),default=0),'max_nodes':max(((w.get('ui_structure')or{}).get('captured_nodes',0) for w in windows),default=0),
             'log_count':len(logs),'max_log_chars':max((len(v.get('text','')) for v in logs),default=0),'log_text':'\n'.join(v.get('text','') for v in logs),
             'image_times':sorted({p['captured_at'] for p in shots}),'text_times':sorted({w['text_captured_at'] for w in windows if w.get('text_captured_at')}),
             'max_image_age':max((r['ts']-w['screenshot']['captured_at'] for r in samples for w in r['desktop'].get('windows',[]) if w['id']==identity.get('window_id') and w.get('screenshot')),default=0),
             'log_times':sorted({w['logs_captured_at'] for w in windows if w.get('logs_captured_at')}),
             'browser_capture_counts':[len(v.get('snapshots',[])) for v in semantics],
             'browser_max_pages':max((len(v.get('snapshots',[])) for v in semantics),default=0),
             'browser_max_chars':max((len(p.get('snapshot',{}).get('text','')) for v in semantics for p in v.get('snapshots',[])),default=0),
             'browser_titles':sorted({p.get('title','') for v in semantics for p in v.get('snapshots',[]) if p.get('snapshot')})}
    return {'metrics':metrics,'count':len(samples),'intervals':intervals,'max_interval':max(intervals,default=0),
            'frames':[{'ts':r['ts'],'settings':r.get('settings'),'available':r['desktop'].get('available'),
                       'screen':r['desktop'].get('desktop_screenshot'),
                       'windows':[{k:w.get(k) for k in ('id','title','focused','visible','ui_text','ui_structure','text_scope','detail_notes','screenshot','logs','text_captured_at','logs_captured_at')} for w in r['desktop'].get('windows',[])],
                       'browser':r.get('browser',{}).get('semantic')} for r in samples],
            'browser_observations':[{'sample_id':r['sample_id'],'ts':r['ts'],**{key:r.get('browser',{}).get('semantic',{}).get(key) for key in ('captured_at','cache_age_seconds','limitations')}} for r in samples],
            'capture_timings':[{'sample_id':r['sample_id'],**r.get('capture_timings',{})} for r in samples]}

def registry(scenario):
    from io_observation import delay,latency,runtime_storage,bridge_rpc,extension_state,stop_delay,disconnect_capture
    return {
    'fault.runtime_storage':lambda step:runtime_storage(scenario,step),
    'fault.io_restore':lambda step:stop_delay(scenario,step),
    'desktop.disconnect_capture':lambda step:disconnect_capture(scenario,step),
    'desktop.rpc':lambda step:bridge_rpc(scenario,step),
    'desktop.extension':lambda step:extension_state(scenario,step),
    'fault.desktop_io_delay':lambda step:delay(scenario,step),
    'desktop.latency':lambda step:latency(scenario,step),
    'sample.inspect':lambda step:sample_inspect(scenario,step),
    'service.observe':lambda step:service_observe(scenario,step),
    'session.save':lambda step:session_save(scenario,step),
    'session.load':lambda step:session_load(scenario,step),
    'backend.connection_probe':lambda step:connection_probe(scenario,step),
    'fault.success_without_action':lambda step:{'closed':True,'injected_fault':True},
    'report.wait':lambda step:report_wait(scenario,step),
    'report.target':lambda step:report_target(scenario,step),
    'report.read':lambda step:scenario.backend.core.store.get('report',step['report_id']),
    'state.wait': lambda step: state_wait(scenario,step),
    'shell.run': lambda step: shell_run(scenario,step),
    'state.read': lambda step: state_read(scenario,step),
    'state.fields': lambda step: state_fields(scenario,step),
    'backend.pause':lambda step:scenario.backend.pause(step['seconds']),
    'backend.restart': lambda step: backend_restart(scenario,step),
    'report.drain': lambda step: report_drain(scenario,step),
    'report.next': lambda step: report_preview(scenario,step),
    'report.reviewed': lambda step: report_release(scenario,step),
    'evidence.inspect': lambda step: evidence_inspect(scenario,step),
}
